// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmogK6VDZVcN4qSuFXLKk5sICoI5hMllI',
    appId: '1:607604025386:web:47484f33af96ec76077b53',
    messagingSenderId: '607604025386',
    projectId: 'projeto-coworking',
    authDomain: 'projeto-coworking.firebaseapp.com',
    storageBucket: 'projeto-coworking.appspot.com',
    measurementId: 'G-ENZCHMVYS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmIBo-OK92xzkQ2cal7qV9JB5wVg0XBns',
    appId: '1:607604025386:android:0404e5cf626de819077b53',
    messagingSenderId: '607604025386',
    projectId: 'projeto-coworking',
    storageBucket: 'projeto-coworking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBegJnT_UxU3RgmDoQAMFhpL_qj-wZF_HQ',
    appId: '1:607604025386:ios:a9bd396020559b8b077b53',
    messagingSenderId: '607604025386',
    projectId: 'projeto-coworking',
    storageBucket: 'projeto-coworking.appspot.com',
    iosBundleId: 'com.example.coworkingApp',
  );
}
